# Generated by Django 5.1.6 on 2025-02-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_dosen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_dosen',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='data_dosen',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
