# Generated by Django 5.1.6 on 2025-02-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_dosen', '0002_data_dosen_joined_date_data_dosen_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_dosen',
            name='Age',
            field=models.IntegerField(null=True),
        ),
    ]
