# Generated by Django 5.1.6 on 2025-02-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_dosen', '0003_data_dosen_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_dosen',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
